#! /bin/bash
gcc -O2 -Wall -W -pedantic -std=c99 -I./include -idirafter ./lap/include \
main.c \
install.c \
docIndex.c \
import_doc.c \
delete_doc.c \
renameDoc.c \
fileop/fileio.c \
fileop/viewIndex.c \
fileop/switchDoc.c \
fileop/readType.c \
fileop/getin.c \
fileop/getcUTF8.c \
fileop/searchItem.c \
fileop/indexCov.c \
fileop/typeCov.c \
process/crlfTo0.c \
process/sitois.c \
process/timeStr.c \
process/arrclean.c \
process/pathOpt.c \
process/getType.c \
process/fill.c \
opendoc/openDoc.c \
opendoc/viewText.c \
opendoc/runSh.c \
opendoc/runBat.c \
opendoc/runPy.c \
opendoc/runC.c \
opendoc/runCpp.c \
options/options.c \
options/help.c \
options/about.c \
options/uninstall.c \
options/reinstall.c \
command/delalldoc.c \
command/cmdSet.c \
command/command.c \
-o odyink_server.out
#./odyink_server.out
