#! /bin/bash
gcc -Wall \
main.c \
install.c \
docIndex.c \
fm/fileio.c \
fm/viewIndex.c \
fm/switchDoc.c \
fm/getin.c \
fm/cleanData.c \
fm/readType.c \
fm/getcUTF8.c \
fm/searchItem.c \
network/getdata.c \
network/getdoc.c \
network/geturl.c \
network/webget.c \
network/write_url.c \
process/crlfTo0.c \
process/sitois.c \
process/arrclean.c \
process/pathOpt.c \
process/getType.c \
opendoc/openDoc.c \
opendoc/viewText.c \
opendoc/runSh.c \
opendoc/runBat.c \
opendoc/runPy.c \
opendoc/runC.c \
opendoc/runCpp.c \
options/options.c \
options/help.c \
options/about.c \
options/uninstall.c \
options/change_website.c \
command/delalldoc.c \
command/cmdSet.c \
command/command.c \
-o OdyinkClient
#./OdyinkClient
